### ISSUE TITLE
The constructor for Switch doesn't handle hasArguments: false

### ISSUE THREAD

**Issue by Zorgle** [bbadjari/ccli#1]
The constructor for Switch ignores hasArguments:false and instead sets number of arguments to UnknownNumberArguments, which leads to an exception being thrown when trying to use a switch created with hasArguments:false--that is, when trying to use it without arguments, an exception is being thrown saying it requires arguments.

Code at issue:

`public Switch(string name, bool hasArguments, bool isRequired)
			: this(name, null, null, UnknownNumberArguments, isRequired)
		{
		}
`

**Comment by Zorgle** [comment]
I created a pull request for this--the bug is simple and the fix is easy.

**Comment by bbadjari** [comment]
Well done. I will add some unit tests to cover this.
